#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#define AUDIO_INPUT_SAMPLE_RATE  16000
#define AUDIO_OUTPUT_SAMPLE_RATE 16000
#define AUDIO_PDM_SAMPLE_RATE    2048000
#define AUTO_START_LISTENING_AFTER_BOOT 0
#define MIC_SELF_TEST_AFTER_BOOT 0

#define AUDIO_I2S_MIC_GPIO_SCK  GPIO_NUM_18
#define AUDIO_I2S_MIC_GPIO_WS   GPIO_NUM_19
#define AUDIO_I2S_MIC_GPIO_DIN  GPIO_NUM_22
#define AUDIO_I2S_SPK_GPIO_DOUT GPIO_NUM_21
#define AUDIO_I2S_SPK_GPIO_BCLK GPIO_NUM_18
#define AUDIO_I2S_SPK_GPIO_LRCK GPIO_NUM_19

#define BUILTIN_LED_GPIO        GPIO_NUM_NC
#define BOOT_BUTTON_GPIO        GPIO_NUM_9
#define TOUCH_BUTTON_GPIO       GPIO_NUM_NC
#define VOLUME_UP_BUTTON_GPIO   GPIO_NUM_NC
#define VOLUME_DOWN_BUTTON_GPIO GPIO_NUM_NC

#endif // _BOARD_CONFIG_H_
